# Generated by Django 3.1.2 on 2022-03-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0006_remove_strideimpactrecord_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='threat',
        ),
        migrations.AddField(
            model_name='risk',
            name='threat_stride',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threat_stride'),
        ),
    ]
