# Generated by Django 3.1.2 on 2022-03-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0007_auto_20220303_1742'),
    ]

    operations = [

        migrations.AddField(
            model_name='threat',
            name='loss_of_accountability',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='loss_of_availability',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='loss_of_confidentiality',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='loss_of_integrity',
            field=models.IntegerField(null=True),
        ),
    ]
