# Generated by Django 3.1.2 on 2022-03-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0008_auto_20220303_1854'),
    ]

    operations = [

        migrations.AddField(
            model_name='risk',
            name='impact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='likelihood',
            field=models.IntegerField(null=True),
        ),
    ]
