# Generated by Django 3.1.2 on 2022-03-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0009_auto_20220303_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='severity',
            field=models.IntegerField(null=True),
        ),
    ]
