# Generated by Django 3.1.2 on 2022-03-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0010_auto_20220303_1956'),
    ]

    operations = [

        migrations.AlterField(
            model_name='risk',
            name='severity',
            field=models.CharField(max_length=100),
        ),
    ]
