# Generated by Django 3.1.2 on 2022-03-03 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0011_auto_20220303_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoofing', models.CharField(max_length=100)),
                ('tampering', models.CharField(max_length=100)),
                ('repudiation', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
                ('dos', models.CharField(max_length=100)),
                ('eop', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.asset')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.process')),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.system')),
            ],
        ),
    ]
